name: .NET MAUI CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'Design/**'
      - 'Assets/**'
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'Design/**'
      - 'Assets/**'

jobs:
  Build_Android:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET v7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./NetMauiGPTApp

      - name: Build Android App
        run: |
          dotnet build ./NetMauiGPTApp -f net7.0-android

  Build_iOS:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET v7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./NetMauiGPTApp

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Build iOS App
        run: |
          dotnet build ./NetMauiGPTApp -f net7.0-ios
          
  Build_MacCatalyst:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET v7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./NetMauiGPTApp

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Build macOS App
        run: |
          dotnet build ./NetMauiGPTApp -f net7.0-maccatalyst

  Build_Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Setup .NET v7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui
          
      - name: Restore NuGet
        run: |
          dotnet restore ./NetMauiGPTApp

      - name: Build Windows App
        run: |
          dotnet build ./NetMauiGPTApp
